// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.DataStore.SQL;

#nullable disable

namespace Plugins.DataStore.SQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreBusiness.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "SofLens 59 6 pk"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "SofLens Daily Disposable 30 pk"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Optima FW 4 pk"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Company = "Оптика № 1",
                            Description = "Описание компании 1",
                            Email = "k1@gmail.com",
                            Fullname = "Иванов И.И.",
                            Name = "Иванов И.И.",
                            Phone = "+375 29 123-12-12"
                        },
                        new
                        {
                            CustomerId = 2,
                            Company = "Оптика Нова",
                            Description = "Описание компании 2",
                            Email = "k2@gmail.com",
                            Fullname = "Петров П.П.",
                            Name = "Петров П.П.",
                            Phone = "+375 29 123-12-13"
                        },
                        new
                        {
                            CustomerId = 3,
                            Company = "ИП Смирнов",
                            Description = "Описание компании 3",
                            Email = "k3@gmail.com",
                            Fullname = "Смирнов С.С.",
                            Name = "Смирнов С.С.",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 4,
                            Company = "Покупатель: 104",
                            Description = "Customer c104",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 104",
                            Name = "Покупатель: 104",
                            Password = "4",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 5,
                            Company = "Покупатель: 105",
                            Description = "Customer c105",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 105",
                            Name = "Покупатель: 105",
                            Password = "5",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 6,
                            Company = "Покупатель: 106",
                            Description = "Customer c106",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 106",
                            Name = "Покупатель: 106",
                            Password = "6",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 7,
                            Company = "Покупатель: 107",
                            Description = "Customer c107",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 107",
                            Name = "Покупатель: 107",
                            Password = "7",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 8,
                            Company = "Покупатель: 108",
                            Description = "Customer c108",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 108",
                            Name = "Покупатель: 108",
                            Password = "8",
                            Phone = "+375 29 123-12-14"
                        },
                        new
                        {
                            CustomerId = 9,
                            Company = "Покупатель: 109",
                            Description = "Customer c109",
                            Email = "k3@gmail.com",
                            Fullname = "Покупатель: 109",
                            Name = "Покупатель: 109",
                            Password = "9",
                            Phone = "+375 29 123-12-14"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.ItemOrder", b =>
                {
                    b.Property<int>("ItemOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemOrderId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderCustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderVendorId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemOrderId");

                    b.HasIndex("OrderCustomerId");

                    b.HasIndex("OrderVendorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ItemOrders");

                    b.HasData(
                        new
                        {
                            ItemOrderId = 1,
                            Description = "Опиасние oc201-io301-ov401 p1001",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4404),
                            OrderCustomerId = 1,
                            OrderVendorId = 1,
                            Price = 1.1100000000000001,
                            ProductId = 1,
                            Quantity = 22
                        },
                        new
                        {
                            ItemOrderId = 2,
                            Description = "Опиасние oc201-io302-ov401 p1002",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4407),
                            OrderCustomerId = 1,
                            OrderVendorId = 1,
                            Price = 2.2200000000000002,
                            ProductId = 2,
                            Quantity = 33
                        },
                        new
                        {
                            ItemOrderId = 3,
                            Description = "Опиасние oc201-io303-ov401 p1003",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4408),
                            OrderCustomerId = 1,
                            OrderVendorId = 1,
                            Price = 3.3300000000000001,
                            ProductId = 3,
                            Quantity = 44
                        },
                        new
                        {
                            ItemOrderId = 4,
                            Description = "Опиасние oc201-io304-ov401 p1004",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4410),
                            OrderCustomerId = 1,
                            OrderVendorId = 1,
                            Price = 4.4400000000000004,
                            ProductId = 4,
                            Quantity = 55
                        },
                        new
                        {
                            ItemOrderId = 5,
                            Description = "Опиасние oc201-io305-ov403 p1005",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4411),
                            OrderCustomerId = 1,
                            Price = 6.4500000000000002,
                            ProductId = 5,
                            Quantity = 855
                        },
                        new
                        {
                            ItemOrderId = 6,
                            Description = "Опиасние oc201-io306-ov404 p1006",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4413),
                            OrderCustomerId = 1,
                            Price = 0.0,
                            ProductId = 6,
                            Quantity = 0
                        },
                        new
                        {
                            ItemOrderId = 7,
                            Description = "Опиасние oc205-io307-ov406 p1008",
                            Edited = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCustomerId = 5,
                            OrderVendorId = 6,
                            Price = 0.0,
                            ProductId = 8,
                            Quantity = 0
                        },
                        new
                        {
                            ItemOrderId = 8,
                            Description = "Опиасние oc209-io308-ov402 p1006",
                            Edited = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCustomerId = 9,
                            OrderVendorId = 2,
                            Price = 0.0,
                            ProductId = 6,
                            Quantity = 0
                        },
                        new
                        {
                            ItemOrderId = 9,
                            Description = "Опиасние oc201-io309-ov408 p1001",
                            Edited = new DateTime(2020, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCustomerId = 1,
                            OrderVendorId = 8,
                            Price = 0.0,
                            ProductId = 1,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderCustomer", b =>
                {
                    b.Property<int>("OrderCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderCustomerId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExcelFileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderCustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrderCustomers");

                    b.HasData(
                        new
                        {
                            OrderCustomerId = 1,
                            CustomerId = 1,
                            Description = "Описание oc201-c101",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4186),
                            ExcelFileId = 1
                        },
                        new
                        {
                            OrderCustomerId = 2,
                            CustomerId = 2,
                            Description = "Описание oc202-c102",
                            Edited = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcelFileId = 2
                        },
                        new
                        {
                            OrderCustomerId = 3,
                            CustomerId = 3,
                            Description = "Описание oc203-c103",
                            Edited = new DateTime(2021, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcelFileId = 3
                        },
                        new
                        {
                            OrderCustomerId = 4,
                            CustomerId = 1,
                            Description = "Описание oc204-c101",
                            Edited = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExcelFileId = 1
                        },
                        new
                        {
                            OrderCustomerId = 5,
                            CustomerId = 9,
                            Description = "Описание ov205-c9",
                            Edited = new DateTime(2020, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 205"
                        },
                        new
                        {
                            OrderCustomerId = 6,
                            CustomerId = 7,
                            Description = "Описание ov206-c7",
                            Edited = new DateTime(2020, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 206"
                        },
                        new
                        {
                            OrderCustomerId = 7,
                            CustomerId = 4,
                            Description = "Описание ov207-c4",
                            Edited = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 207"
                        },
                        new
                        {
                            OrderCustomerId = 8,
                            CustomerId = 6,
                            Description = "Описание ov208-c6",
                            Edited = new DateTime(2020, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 208"
                        },
                        new
                        {
                            OrderCustomerId = 9,
                            CustomerId = 8,
                            Description = "Описание ov209-c8",
                            Edited = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 209"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderVendor", b =>
                {
                    b.Property<int>("OrderVendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderVendorId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("OrderVendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("OrderVendors");

                    b.HasData(
                        new
                        {
                            OrderVendorId = 1,
                            Description = "Описание ov401",
                            Edited = new DateTime(2022, 2, 6, 19, 13, 57, 721, DateTimeKind.Local).AddTicks(4358),
                            Name = "OrderVendor-401",
                            VendorId = 1
                        },
                        new
                        {
                            OrderVendorId = 2,
                            Description = "Описание 402-7",
                            Edited = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 402",
                            VendorId = 7
                        },
                        new
                        {
                            OrderVendorId = 3,
                            Description = "Описание 403-5",
                            Edited = new DateTime(2021, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 403",
                            VendorId = 5
                        },
                        new
                        {
                            OrderVendorId = 4,
                            Description = "Описание 404-9",
                            Edited = new DateTime(2022, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 404",
                            VendorId = 9
                        },
                        new
                        {
                            OrderVendorId = 5,
                            Description = "Описание 405-4",
                            Edited = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 405",
                            VendorId = 4
                        },
                        new
                        {
                            OrderVendorId = 6,
                            Description = "Описание 406-3",
                            Edited = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 406",
                            VendorId = 3
                        },
                        new
                        {
                            OrderVendorId = 7,
                            Description = "Описание 407-2",
                            Edited = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 407",
                            VendorId = 2
                        },
                        new
                        {
                            OrderVendorId = 8,
                            Description = "Описание 408-9",
                            Edited = new DateTime(2021, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 408",
                            VendorId = 9
                        },
                        new
                        {
                            OrderVendorId = 9,
                            Description = "Описание 409-8",
                            Edited = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OrderVendor: 409",
                            VendorId = 8
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("BC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sph")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C4",
                            Description = "Описание 1001",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-0.50"
                        },
                        new
                        {
                            ProductId = 2,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C5",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-0.75"
                        },
                        new
                        {
                            ProductId = 3,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C6",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.00"
                        },
                        new
                        {
                            ProductId = 4,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C7",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.25"
                        },
                        new
                        {
                            ProductId = 5,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C8",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.50"
                        },
                        new
                        {
                            ProductId = 6,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C9",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.75"
                        },
                        new
                        {
                            ProductId = 7,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C10",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.00"
                        },
                        new
                        {
                            ProductId = 8,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C11",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.25"
                        },
                        new
                        {
                            ProductId = 9,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C12",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.50"
                        },
                        new
                        {
                            ProductId = 10,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C13",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.75"
                        },
                        new
                        {
                            ProductId = 11,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C14",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.00"
                        },
                        new
                        {
                            ProductId = 12,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C15",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.25"
                        },
                        new
                        {
                            ProductId = 13,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C16",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.50"
                        },
                        new
                        {
                            ProductId = 14,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C17",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.75"
                        },
                        new
                        {
                            ProductId = 15,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C18",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.00"
                        },
                        new
                        {
                            ProductId = 16,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C19",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.25"
                        },
                        new
                        {
                            ProductId = 17,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C20",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.50"
                        },
                        new
                        {
                            ProductId = 18,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C21",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.75"
                        },
                        new
                        {
                            ProductId = 19,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C22",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.00"
                        },
                        new
                        {
                            ProductId = 20,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C23",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.25"
                        },
                        new
                        {
                            ProductId = 21,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C24",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.50"
                        },
                        new
                        {
                            ProductId = 22,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C25",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.75"
                        },
                        new
                        {
                            ProductId = 23,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C26",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-6.00"
                        },
                        new
                        {
                            ProductId = 24,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C27",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-6.50"
                        },
                        new
                        {
                            ProductId = 25,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C28",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-7.00"
                        },
                        new
                        {
                            ProductId = 26,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C29",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-7.50"
                        },
                        new
                        {
                            ProductId = 27,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C30",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-8.00"
                        },
                        new
                        {
                            ProductId = 28,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C31",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-8.50"
                        },
                        new
                        {
                            ProductId = 29,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "C32",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-9.00"
                        },
                        new
                        {
                            ProductId = 30,
                            BC = "",
                            CategoryId = 1,
                            Cell = "",
                            Name = "",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = ""
                        },
                        new
                        {
                            ProductId = 31,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E5",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+0.75"
                        },
                        new
                        {
                            ProductId = 32,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E6",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.00"
                        },
                        new
                        {
                            ProductId = 33,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E7",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.25"
                        },
                        new
                        {
                            ProductId = 34,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E8",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.50"
                        },
                        new
                        {
                            ProductId = 35,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E9",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.75"
                        },
                        new
                        {
                            ProductId = 36,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E10",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.00"
                        },
                        new
                        {
                            ProductId = 37,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E11",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.25"
                        },
                        new
                        {
                            ProductId = 38,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E12",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.50"
                        },
                        new
                        {
                            ProductId = 39,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E13",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.75"
                        },
                        new
                        {
                            ProductId = 40,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E14",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.00"
                        },
                        new
                        {
                            ProductId = 41,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E15",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.25"
                        },
                        new
                        {
                            ProductId = 42,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E16",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.50"
                        },
                        new
                        {
                            ProductId = 43,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E17",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.75"
                        },
                        new
                        {
                            ProductId = 44,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E18",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.00"
                        },
                        new
                        {
                            ProductId = 45,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E19",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.25"
                        },
                        new
                        {
                            ProductId = 46,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E20",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.50"
                        },
                        new
                        {
                            ProductId = 47,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E21",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.75"
                        },
                        new
                        {
                            ProductId = 48,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E22",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.00"
                        },
                        new
                        {
                            ProductId = 49,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E23",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.25"
                        },
                        new
                        {
                            ProductId = 50,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E24",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.50"
                        },
                        new
                        {
                            ProductId = 51,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E25",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.75"
                        },
                        new
                        {
                            ProductId = 52,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "E26",
                            Name = "SofLens 59 6 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+6.00"
                        },
                        new
                        {
                            ProductId = 53,
                            BC = "",
                            CategoryId = 1,
                            Cell = "",
                            Name = "",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = ""
                        },
                        new
                        {
                            ProductId = 54,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H5",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-0.75"
                        },
                        new
                        {
                            ProductId = 55,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H6",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.00"
                        },
                        new
                        {
                            ProductId = 56,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H7",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.25"
                        },
                        new
                        {
                            ProductId = 57,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H8",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.50"
                        },
                        new
                        {
                            ProductId = 58,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H9",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-1.75"
                        },
                        new
                        {
                            ProductId = 59,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H10",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.00"
                        },
                        new
                        {
                            ProductId = 60,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H11",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.25"
                        },
                        new
                        {
                            ProductId = 61,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H12",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.50"
                        },
                        new
                        {
                            ProductId = 62,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H13",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-2.75"
                        },
                        new
                        {
                            ProductId = 63,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H14",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.00"
                        },
                        new
                        {
                            ProductId = 64,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H15",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.25"
                        },
                        new
                        {
                            ProductId = 65,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H16",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.50"
                        },
                        new
                        {
                            ProductId = 66,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H17",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-3.75"
                        },
                        new
                        {
                            ProductId = 67,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H18",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.00"
                        },
                        new
                        {
                            ProductId = 68,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H19",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.25"
                        },
                        new
                        {
                            ProductId = 69,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H20",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.50"
                        },
                        new
                        {
                            ProductId = 70,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H21",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-4.75"
                        },
                        new
                        {
                            ProductId = 71,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H22",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.00"
                        },
                        new
                        {
                            ProductId = 72,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H23",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.25"
                        },
                        new
                        {
                            ProductId = 73,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H24",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.50"
                        },
                        new
                        {
                            ProductId = 74,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H25",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-5.75"
                        },
                        new
                        {
                            ProductId = 75,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H26",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-6.00"
                        },
                        new
                        {
                            ProductId = 76,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H27",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-6.50"
                        },
                        new
                        {
                            ProductId = 77,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H28",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-7.00"
                        },
                        new
                        {
                            ProductId = 78,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H29",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-7.50"
                        },
                        new
                        {
                            ProductId = 79,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H30",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-8.00"
                        },
                        new
                        {
                            ProductId = 80,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H31",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-8.50"
                        },
                        new
                        {
                            ProductId = 81,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "H32",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "-9.00"
                        },
                        new
                        {
                            ProductId = 82,
                            BC = "",
                            CategoryId = 1,
                            Cell = "",
                            Name = "",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = ""
                        },
                        new
                        {
                            ProductId = 83,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J5",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+0.75"
                        },
                        new
                        {
                            ProductId = 84,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J6",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.00"
                        },
                        new
                        {
                            ProductId = 85,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J7",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.25"
                        },
                        new
                        {
                            ProductId = 86,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J8",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.50"
                        },
                        new
                        {
                            ProductId = 87,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J9",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+1.75"
                        },
                        new
                        {
                            ProductId = 88,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J10",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.00"
                        },
                        new
                        {
                            ProductId = 89,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J11",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.25"
                        },
                        new
                        {
                            ProductId = 90,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J12",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.50"
                        },
                        new
                        {
                            ProductId = 91,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J13",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+2.75"
                        },
                        new
                        {
                            ProductId = 92,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J14",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.00"
                        },
                        new
                        {
                            ProductId = 93,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J15",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.25"
                        },
                        new
                        {
                            ProductId = 94,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J16",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.50"
                        },
                        new
                        {
                            ProductId = 95,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J17",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+3.75"
                        },
                        new
                        {
                            ProductId = 96,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J18",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.00"
                        },
                        new
                        {
                            ProductId = 97,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J19",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.25"
                        },
                        new
                        {
                            ProductId = 98,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J20",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.50"
                        },
                        new
                        {
                            ProductId = 99,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J21",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+4.75"
                        },
                        new
                        {
                            ProductId = 100,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J22",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.00"
                        },
                        new
                        {
                            ProductId = 101,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J23",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.25"
                        },
                        new
                        {
                            ProductId = 102,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J24",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.50"
                        },
                        new
                        {
                            ProductId = 103,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J25",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+5.75"
                        },
                        new
                        {
                            ProductId = 104,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J26",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+6.00"
                        },
                        new
                        {
                            ProductId = 105,
                            BC = " 8.6",
                            CategoryId = 1,
                            Cell = "J27",
                            Name = " SofLens Daily Disposable 30 pk",
                            Price = 1.0,
                            Quantity = 1,
                            Sph = "+6.50"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"), 1L, 1);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            VendorId = 1,
                            Company = "Поставщик № 501",
                            Description = "Описание p501",
                            Email = "mail-501@gmail.com",
                            Name = "Поставщик № 501"
                        },
                        new
                        {
                            VendorId = 2,
                            Company = "Поставщик: 502",
                            Description = "Описание p502-1",
                            Email = "mail-502@gmail.com",
                            Name = "Поставщик: 502"
                        },
                        new
                        {
                            VendorId = 3,
                            Company = "Поставщик: 503",
                            Description = "Описание p503-8",
                            Email = "mail-503@gmail.com",
                            Name = "Поставщик: 503"
                        },
                        new
                        {
                            VendorId = 4,
                            Company = "Поставщик: 504",
                            Description = "Описание p504-9",
                            Email = "mail-504@gmail.com",
                            Name = "Поставщик: 504"
                        },
                        new
                        {
                            VendorId = 5,
                            Company = "Поставщик: 505",
                            Description = "Описание p505-7",
                            Email = "mail-505@gmail.com",
                            Name = "Поставщик: 505"
                        },
                        new
                        {
                            VendorId = 6,
                            Company = "Поставщик: 506",
                            Description = "Описание p506-3",
                            Email = "mail-506@gmail.com",
                            Name = "Поставщик: 506"
                        },
                        new
                        {
                            VendorId = 7,
                            Company = "Поставщик: 507",
                            Description = "Описание p507-6",
                            Email = "mail-507@gmail.com",
                            Name = "Поставщик: 507"
                        },
                        new
                        {
                            VendorId = 8,
                            Company = "Поставщик: 508",
                            Description = "Описание p508-4",
                            Email = "mail-508@gmail.com",
                            Name = "Поставщик: 508"
                        },
                        new
                        {
                            VendorId = 9,
                            Company = "Поставщик: 509",
                            Description = "Описание p509-2",
                            Email = "mail-509@gmail.com",
                            Name = "Поставщик: 509"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Models.ItemOrder", b =>
                {
                    b.HasOne("CoreBusiness.Models.OrderCustomer", "OrderCustomer")
                        .WithMany("ItemOrders")
                        .HasForeignKey("OrderCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreBusiness.Models.OrderVendor", "OrderVendor")
                        .WithMany("ItemOrders")
                        .HasForeignKey("OrderVendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoreBusiness.Models.Product", "Product")
                        .WithMany("ItemOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderCustomer");

                    b.Navigation("OrderVendor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderCustomer", b =>
                {
                    b.HasOne("CoreBusiness.Models.Customer", "Customer")
                        .WithMany("OrderCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderVendor", b =>
                {
                    b.HasOne("CoreBusiness.Models.Vendor", "Vendor")
                        .WithMany("OrderVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CoreBusiness.Models.Product", b =>
                {
                    b.HasOne("CoreBusiness.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoreBusiness.Models.Customer", b =>
                {
                    b.Navigation("OrderCustomers");
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderCustomer", b =>
                {
                    b.Navigation("ItemOrders");
                });

            modelBuilder.Entity("CoreBusiness.Models.OrderVendor", b =>
                {
                    b.Navigation("ItemOrders");
                });

            modelBuilder.Entity("CoreBusiness.Models.Product", b =>
                {
                    b.Navigation("ItemOrders");
                });

            modelBuilder.Entity("CoreBusiness.Models.Vendor", b =>
                {
                    b.Navigation("OrderVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
