using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CoreBusiness.Models;
using Microsoft.EntityFrameworkCore;

namespace Plugins.DataStore.SQL
{
    public class AppDbContext : DbContext
    {
        #region public DbSets
        public DbSet<Category> Categories { get; set; } = null;
        public DbSet<Product> Products { get; set; } = null;
        public DbSet<Customer> Customers { get; set; } = null;
        public DbSet<OrderCustomer> OrderCustomers { get; set; } = null;
        public DbSet<ItemOrder> ItemOrders { get; set; } = null;
        public DbSet<OrderVendor> OrderVendors { get; set; } = null;
        public DbSet<Vendor> Vendors { get; set; } = null;

        public DbSet<FileModel> Files { get; set; }
        #endregion

        public AppDbContext() { }

        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    optionsBuilder.UseSqlServer(@"Data Source=PC-631\SQLEXPRESS;Initial Catalog=WebOptixSuccess;Integrated Security=True;Pooling=False");
        //    //optionsBuilder.UseSqlServer(@"Data Source=motiv-laptop\sqlexpress;Initial Catalog=WebOptixSuccess;Integrated Security=True;Pooling=False");
        //}

        public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Category>()
                .HasMany(c => c.Products)
                .WithOne(p => p.Category)
                .HasForeignKey(p => p.CategoryId)
                .OnDelete(DeleteBehavior.SetNull);

            modelBuilder.Entity<Customer>()
                .HasMany(c => c.OrderCustomers)
                .WithOne(p => p.Customer)
                .HasForeignKey(p => p.CustomerId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<Vendor>()
                .HasMany(c => c.OrderVendors)
                .WithOne(p => p.Vendor)
                .HasForeignKey(p => p.VendorId)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<OrderCustomer>()
               .HasMany(c => c.ItemOrders)
               .WithOne(p => p.OrderCustomer)
               .HasForeignKey(p => p.OrderCustomerId)
               .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<OrderVendor>()
               .HasMany(c => c.ItemOrders)
               .WithOne(p => p.OrderVendor)
               .HasForeignKey(p => p.OrderVendorId)
               .OnDelete(DeleteBehavior.SetNull);

            modelBuilder.Entity<Product>()
               .HasMany(c => c.ItemOrders)
               .WithOne(p => p.Product)
               .HasForeignKey(p => p.ProductId);

            // seeding some data
            modelBuilder.Entity<Category>().HasData(new[]{
                new Category() { CategoryId = 1, Name = "SofLens 59 6 pk" },
                new Category() { CategoryId = 2, Name = "SofLens Daily Disposable 30 pk" },
                new Category() { CategoryId = 3, Name = "Optima FW 4 pk" }
            });

            int productId = 0;
            var products = new List<Product>() { 
                new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-0.50", Cell = "C4", Quantity = 1, Price = 1.00, Description = "Описание 1001"},
                #region Product 2-100
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-0.75", Cell = "C5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-1.00", Cell = "C6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-1.25", Cell = "C7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-1.50", Cell = "C8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-1.75", Cell = "C9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-2.00", Cell = "C10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-2.25", Cell = "C11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-2.50", Cell = "C12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-2.75", Cell = "C13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-3.00", Cell = "C14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-3.25", Cell = "C15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-3.50", Cell = "C16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-3.75", Cell = "C17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-4.00", Cell = "C18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-4.25", Cell = "C19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-4.50", Cell = "C20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-4.75", Cell = "C21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-5.00", Cell = "C22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-5.25", Cell = "C23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-5.50", Cell = "C24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-5.75", Cell = "C25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-6.00", Cell = "C26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-6.50", Cell = "C27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-7.00", Cell = "C28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-7.50", Cell = "C29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-8.00", Cell = "C30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-8.50", Cell = "C31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "-9.00", Cell = "C32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+0.75", Cell = "E5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+1.00", Cell = "E6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+1.25", Cell = "E7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+1.50", Cell = "E8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+1.75", Cell = "E9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+2.00", Cell = "E10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+2.25", Cell = "E11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+2.50", Cell = "E12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+2.75", Cell = "E13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+3.00", Cell = "E14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+3.25", Cell = "E15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+3.50", Cell = "E16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+3.75", Cell = "E17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+4.00", Cell = "E18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+4.25", Cell = "E19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+4.50", Cell = "E20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+4.75", Cell = "E21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+5.00", Cell = "E22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+5.25", Cell = "E23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+5.50", Cell = "E24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+5.75", Cell = "E25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "SofLens 59 6 pk", BC = " 8.6", Sph = "+6.00", Cell = "E26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-0.75", Cell = "H5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-1.00", Cell = "H6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-1.25", Cell = "H7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-1.50", Cell = "H8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-1.75", Cell = "H9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-2.00", Cell = "H10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-2.25", Cell = "H11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-2.50", Cell = "H12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-2.75", Cell = "H13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-3.00", Cell = "H14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-3.25", Cell = "H15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-3.50", Cell = "H16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-3.75", Cell = "H17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-4.00", Cell = "H18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-4.25", Cell = "H19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-4.50", Cell = "H20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-4.75", Cell = "H21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-5.00", Cell = "H22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-5.25", Cell = "H23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-5.50", Cell = "H24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-5.75", Cell = "H25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-6.00", Cell = "H26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-6.50", Cell = "H27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-7.00", Cell = "H28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-7.50", Cell = "H29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-8.00", Cell = "H30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-8.50", Cell = "H31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "-9.00", Cell = "H32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+0.75", Cell = "J5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+1.00", Cell = "J6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+1.25", Cell = "J7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+1.50", Cell = "J8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+1.75", Cell = "J9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+2.00", Cell = "J10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+2.25", Cell = "J11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+2.50", Cell = "J12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+2.75", Cell = "J13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+3.00", Cell = "J14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+3.25", Cell = "J15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+3.50", Cell = "J16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+3.75", Cell = "J17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+4.00", Cell = "J18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+4.25", Cell = "J19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+4.50", Cell = "J20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+4.75", Cell = "J21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+5.00", Cell = "J22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+5.25", Cell = "J23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+5.50", Cell = "J24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+5.75", Cell = "J25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+6.00", Cell = "J26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 30 pk", BC = " 8.6", Sph = "+6.50", Cell = "J27", Quantity = 1, Price = 1.00},
            #endregion Product 2 - 1xx

            #region Product 1xx - 5xx
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-0.75", Cell = "m5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-1.00", Cell = "m6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-1.25", Cell = "m7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-1.50", Cell = "m8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-1.75", Cell = "m9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-2.00", Cell = "m10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-2.25", Cell = "m11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-2.50", Cell = "m12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-2.75", Cell = "m13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-3.00", Cell = "m14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-3.25", Cell = "m15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-3.50", Cell = "m16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-3.75", Cell = "m17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-4.00", Cell = "m18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-4.25", Cell = "m19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-4.50", Cell = "m20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-4.75", Cell = "m21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-5.00", Cell = "m22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-5.25", Cell = "m23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-5.50", Cell = "m24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-5.75", Cell = "m25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-6.00", Cell = "m26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-6.50", Cell = "m27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-7.00", Cell = "m28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-7.50", Cell = "m29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-8.00", Cell = "m30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-8.50", Cell = "m31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "-9.00", Cell = "m32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+0.75", Cell = "o5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+1.00", Cell = "o6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+1.25", Cell = "o7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+1.50", Cell = "o8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+1.75", Cell = "o9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+2.00", Cell = "o10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+2.25", Cell = "o11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+2.50", Cell = "o12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+2.75", Cell = "o13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+3.00", Cell = "o14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+3.25", Cell = "o15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+3.50", Cell = "o16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+3.75", Cell = "o17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+4.00", Cell = "o18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+4.25", Cell = "o19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+4.50", Cell = "o20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+4.75", Cell = "o21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+5.00", Cell = "o22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+5.25", Cell = "o23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+5.50", Cell = "o24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+5.75", Cell = "o25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+6.00", Cell = "o26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = " SofLens Daily Disposable 90 pk", BC = " 8.6", Sph = "+6.50", Cell = "o27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-0.75", Cell = "r5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-1.00", Cell = "r6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-1.25", Cell = "r7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-1.50", Cell = "r8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-1.75", Cell = "r9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-2.00", Cell = "r10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-2.25", Cell = "r11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-2.50", Cell = "r12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-2.75", Cell = "r13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-3.00", Cell = "r14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-3.25", Cell = "r15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-3.50", Cell = "r16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-3.75", Cell = "r17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-4.00", Cell = "r18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-4.25", Cell = "r19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-4.50", Cell = "r20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-4.75", Cell = "r21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-5.00", Cell = "r22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-5.25", Cell = "r23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-5.50", Cell = "r24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-5.75", Cell = "r25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-6.00", Cell = "r26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-6.50", Cell = "r27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-7.00", Cell = "r28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-7.50", Cell = "r29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-8.00", Cell = "r30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-8.50", Cell = "r31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.4", Sph = "-9.00", Cell = "r32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-0.75", Cell = "s5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-1.00", Cell = "s6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-1.25", Cell = "s7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-1.50", Cell = "s8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-1.75", Cell = "s9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-2.00", Cell = "s10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-2.25", Cell = "s11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-2.50", Cell = "s12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-2.75", Cell = "s13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-3.00", Cell = "s14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-3.25", Cell = "s15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-3.50", Cell = "s16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-3.75", Cell = "s17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-4.00", Cell = "s18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-4.25", Cell = "s19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-4.50", Cell = "s20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-4.75", Cell = "s21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-5.00", Cell = "s22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-5.25", Cell = "s23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-5.50", Cell = "s24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-5.75", Cell = "s25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-6.00", Cell = "s26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-6.50", Cell = "s27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-7.00", Cell = "s28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-7.50", Cell = "s29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-8.00", Cell = "s30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-8.50", Cell = "s31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = " 8.7", Sph = "-9.00", Cell = "s32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-0.75", Cell = "t5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-1.00", Cell = "t6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-1.25", Cell = "t7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-1.50", Cell = "t8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-1.75", Cell = "t9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-2.00", Cell = "t10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-2.25", Cell = "t11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-2.50", Cell = "t12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-2.75", Cell = "t13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-3.00", Cell = "t14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-3.25", Cell = "t15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-3.50", Cell = "t16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-3.75", Cell = "t17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-4.00", Cell = "t18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-4.25", Cell = "t19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-4.50", Cell = "t20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-4.75", Cell = "t21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-5.00", Cell = "t22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-5.25", Cell = "t23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-5.50", Cell = "t24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-5.75", Cell = "t25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-6.00", Cell = "t26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-6.50", Cell = "t27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-7.00", Cell = "t28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-7.50", Cell = "t29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-8.00", Cell = "t30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-8.50", Cell = "t31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Optima FW 4 pk", BC = "9.0", Sph = "-9.00", Cell = "t32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-0.50", Cell = "x5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-0.75", Cell = "x6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-1.00", Cell = "x7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-1.25", Cell = "x8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-1.50", Cell = "x9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-1.75", Cell = "x10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-2.00", Cell = "x11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-2.25", Cell = "x12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-2.50", Cell = "x13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-2.75", Cell = "x14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-3.00", Cell = "x15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-3.25", Cell = "x16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-3.50", Cell = "x17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-3.75", Cell = "x18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-4.00", Cell = "x19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-4.25", Cell = "x20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-4.50", Cell = "x21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-4.75", Cell = "x22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-5.00", Cell = "x23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-5.25", Cell = "x24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-5.50", Cell = "x25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-5.75", Cell = "x26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-6.00", Cell = "x27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-6.50", Cell = "x28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-7.00", Cell = "x29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-7.50", Cell = "x30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-8.00", Cell = "x31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-8.50", Cell = "x32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-9.00", Cell = "x33", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-9.50", Cell = "x34", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-10.00", Cell = "x35", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-10.50", Cell = "x36", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-11.00", Cell = "x37", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-11.50", Cell = "x38", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "-12.00", Cell = "x39", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+0.50", Cell = "z5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+0.75", Cell = "z6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+1.00", Cell = "z7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+1.25", Cell = "z8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+1.50", Cell = "z9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+1.75", Cell = "z10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+2.00", Cell = "z11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+2.25", Cell = "z12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+2.50", Cell = "z13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+2.75", Cell = "z14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+3.00", Cell = "z15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+3.25", Cell = "z16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+3.50", Cell = "z17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+3.75", Cell = "z18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+4.00", Cell = "z19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+4.25", Cell = "z20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+4.50", Cell = "z21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+4.75", Cell = "z22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+5.00", Cell = "z23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+5.25", Cell = "z24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+5.50", Cell = "z25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+5.75", Cell = "z26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Pure Vision2 6pk", BC = " 8.6", Sph = "+6.00", Cell = "z27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-0.50", Cell = "ac5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-0.75", Cell = "ac6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-1.00", Cell = "ac7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-1.25", Cell = "ac8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-1.50", Cell = "ac9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-1.75", Cell = "ac10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-2.00", Cell = "ac11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-2.25", Cell = "ac12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-2.50", Cell = "ac13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-2.75", Cell = "ac14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-3.00", Cell = "ac15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-3.25", Cell = "ac16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-3.50", Cell = "ac17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-3.75", Cell = "ac18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-4.00", Cell = "ac19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-4.25", Cell = "ac20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-4.50", Cell = "ac21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-4.75", Cell = "ac22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-5.00", Cell = "ac23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-5.25", Cell = "ac24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-5.50", Cell = "ac25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-5.75", Cell = "ac26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-6.00", Cell = "ac27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-6.25", Cell = "ac28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-6.50", Cell = "ac29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-7.00", Cell = "ac30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-7.50", Cell = "ac31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-8.00", Cell = "ac32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-8.50", Cell = "ac33", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-9.00", Cell = "ac34", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+0.50", Cell = "ae5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+0.75", Cell = "ae6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+1.00", Cell = "ae7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+1.25", Cell = "ae8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+1.50", Cell = "ae9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+1.75", Cell = "ae10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+2.00", Cell = "ae11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+2.25", Cell = "ae12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+2.50", Cell = "ae13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+2.75", Cell = "ae14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+3.00", Cell = "ae15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+3.25", Cell = "ae16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+3.50", Cell = "ae17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+3.75", Cell = "ae18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+4.00", Cell = "ae19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+4.25", Cell = "ae20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+4.50", Cell = "ae21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+4.75", Cell = "ae22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+5.00", Cell = "ae23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+5.25", Cell = "ae24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+5.50", Cell = "ae25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+5.75", Cell = "ae26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+6.00", Cell = "ae27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "-6.25", Cell = "ae28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 30pk", BC = " 8.6", Sph = "+6.50", Cell = "ae29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-0.50", Cell = "ag5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-0.75", Cell = "ag6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-1.00", Cell = "ag7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-1.25", Cell = "ag8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-1.50", Cell = "ag9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-1.75", Cell = "ag10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-2.00", Cell = "ag11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-2.25", Cell = "ag12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-2.50", Cell = "ag13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-2.75", Cell = "ag14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-3.00", Cell = "ag15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-3.25", Cell = "ag16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-3.50", Cell = "ag17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-3.75", Cell = "ag18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-4.00", Cell = "ag19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-4.25", Cell = "ag20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-4.50", Cell = "ag21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-4.75", Cell = "ag22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-5.00", Cell = "ag23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-5.25", Cell = "ag24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-5.50", Cell = "ag25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-5.75", Cell = "ag26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-6.00", Cell = "ag27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-6.25", Cell = "ag28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-6.50", Cell = "ag29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-7.00", Cell = "ag30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-7.50", Cell = "ag31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-8.00", Cell = "ag32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-8.50", Cell = "ag33", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "-9.00", Cell = "ag34", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+0.50", Cell = "ai5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+0.75", Cell = "ai6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+1.00", Cell = "ai7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+1.25", Cell = "ai8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+1.50", Cell = "ai9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+1.75", Cell = "ai10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+2.00", Cell = "ai11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+2.25", Cell = "ai12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+2.50", Cell = "ai13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+2.75", Cell = "ai14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+3.00", Cell = "ai15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+3.25", Cell = "ai16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+3.50", Cell = "ai17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+3.75", Cell = "ai18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+4.00", Cell = "ai19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+4.25", Cell = "ai20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+4.50", Cell = "ai21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+4.75", Cell = "ai22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+5.00", Cell = "ai23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+5.25", Cell = "ai24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+5.50", Cell = "ai25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+5.75", Cell = "ai26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+6.00", Cell = "ai27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+6.50", Cell = "ai28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Biotrue ONEDay 90pk", BC = " 8.6", Sph = "+6.50", Cell = "ai29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-0.25", Cell = "al5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-0.50", Cell = "al6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-0.75", Cell = "al7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-1.00", Cell = "al8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-1.25", Cell = "al9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-1.50", Cell = "al10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-1.75", Cell = "al11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-2.00", Cell = "al12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-2.25", Cell = "al13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-2.50", Cell = "al14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-2.75", Cell = "al15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-3.00", Cell = "al16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-3.25", Cell = "al17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-3.50", Cell = "al18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-3.75", Cell = "al19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-4.00", Cell = "al20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-4.25", Cell = "al21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-4.50", Cell = "al22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-4.75", Cell = "al23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-5.00", Cell = "al24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-5.25", Cell = "al25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-5.50", Cell = "al26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-5.75", Cell = "al27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-6.00", Cell = "al28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-6.50", Cell = "al29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-7.00", Cell = "al30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-7.50", Cell = "al31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-8.00", Cell = "al32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-8.50", Cell = "al33", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-9.00", Cell = "al34", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-9.50", Cell = "al35", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-10.00", Cell = "al36", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-10.50", Cell = "al37", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-11.00", Cell = "al38", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-11.50", Cell = "al39", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "-12.00", Cell = "al40", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+0.25", Cell = "an5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+0.50", Cell = "an6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+0.75", Cell = "an7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+1.00", Cell = "an8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+1.25", Cell = "an9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+1.50", Cell = "an10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+1.75", Cell = "an11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+2.00", Cell = "an12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+2.25", Cell = "an13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+2.50", Cell = "an14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+2.75", Cell = "an15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+3.00", Cell = "an16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+3.25", Cell = "an17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+3.50", Cell = "an18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+3.75", Cell = "an19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+4.00", Cell = "an20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+4.25", Cell = "an21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+4.50", Cell = "an22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+4.75", Cell = "an23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+5.00", Cell = "an24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+5.25", Cell = "an25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+5.50", Cell = "an26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+5.75", Cell = "an27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 3pk", BC = " 8.5", Sph = "+6.00", Cell = "an28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-0.25", Cell = "aq5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-0.50", Cell = "aq6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-0.75", Cell = "aq7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-1.00", Cell = "aq8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-1.25", Cell = "aq9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-1.50", Cell = "aq10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-1.75", Cell = "aq11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-2.00", Cell = "aq12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-2.25", Cell = "aq13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-2.50", Cell = "aq14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-2.75", Cell = "aq15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-3.00", Cell = "aq16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-3.25", Cell = "aq17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-3.50", Cell = "aq18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-3.75", Cell = "aq19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-4.00", Cell = "aq20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-4.25", Cell = "aq21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-4.50", Cell = "aq22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-4.75", Cell = "aq23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-5.00", Cell = "aq24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-5.25", Cell = "aq25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-5.50", Cell = "aq26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-5.75", Cell = "aq27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-6.00", Cell = "aq28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-6.50", Cell = "aq29", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-7.00", Cell = "aq30", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-7.50", Cell = "aq31", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-8.00", Cell = "aq32", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-8.50", Cell = "aq33", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-9.00", Cell = "aq34", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-9.50", Cell = "aq35", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-10.00", Cell = "aq36", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-10.50", Cell = "aq37", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-11.00", Cell = "aq38", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-11.50", Cell = "aq39", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "-12.00", Cell = "aq40", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+0.25", Cell = "as5", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+0.50", Cell = "as6", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+0.75", Cell = "as7", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+1.00", Cell = "as8", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+1.25", Cell = "as9", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+1.50", Cell = "as10", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+1.75", Cell = "as11", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+2.00", Cell = "as12", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+2.25", Cell = "as13", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+2.50", Cell = "as14", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+2.75", Cell = "as15", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+3.00", Cell = "as16", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+3.25", Cell = "as17", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+3.50", Cell = "as18", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+3.75", Cell = "as19", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+4.00", Cell = "as20", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+4.25", Cell = "as21", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+4.50", Cell = "as22", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+4.75", Cell = "as23", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+5.00", Cell = "as24", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+5.25", Cell = "as25", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+5.50", Cell = "as26", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+5.75", Cell = "as27", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "ULTRA 6pk", BC = " 8.5", Sph = "+6.00", Cell = "as28", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu Multiplus 120 мл", BC = "", Sph = "", Cell = "e38", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu Multiplus 240 мл", BC = "", Sph = "", Cell = "e39", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu Multiplus 360 мл", BC = "", Sph = "", Cell = "e40", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu MPS 120", BC = "", Sph = "", Cell = "e41", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu MPS 240", BC = "", Sph = "", Cell = "e42", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор ReNu MPS 360", BC = "", Sph = "", Cell = "e43", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор BIOTRUE 120", BC = "", Sph = "", Cell = "e44", Quantity = 1, Price = 1.00},
new Product { ProductId = ++productId, CategoryId = 1, Name = "Раствор BIOTRUE 300", BC = "", Sph = "", Cell = "e45", Quantity = 1, Price = 1.00}

                #endregion Product 1xx - 5xx
            };

            modelBuilder.Entity<Product>().HasData(products);

            DemoData demoData = new(products, 100);

            // Add Customer
            modelBuilder.Entity<Customer>().HasData(demoData.GetCustomers());
            // Add OrderCustomer
            modelBuilder.Entity<OrderCustomer>().HasData(demoData.GetOrderCustomers());
            // Add Vendor
            modelBuilder.Entity<Vendor>().HasData(demoData.GetVendors());
            // Add OrderVendor
            modelBuilder.Entity<OrderVendor>().HasData(demoData.GetOrderVendors());
            // Add ItemOrders
            modelBuilder.Entity<ItemOrder>().HasData(demoData.GetItemOrders());
        }        
    }
}